databases:
  - name: whatsplaying-db
    databaseName: whatsplaying
    user: whatsplaying
    region: oregon

services:
  - type: web
    name: whatsplaying
    runtime: python
    region: oregon
    buildCommand: "./build.sh"
    startCommand: "gunicorn whatsplaying.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: whatsplaying-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DJANGO_SETTINGS_MODULE
        value: whatsplaying.settings_production
      - key: TMDB_API_KEY
        value: 0e828944007b04e03ec49fa43f5679a3
      - key: PYTHON_VERSION
        value: 3.11.0